---
swagger: "2.0"
info:
  description: "API Guide for accessing MLP API"
  version: "0.4.0"
  title: "MLP API"
host: "localhost:8080"
basePath: "/"
tags:
- name: "project"
  description: "Project Management API. Project is used to namespace model, secret,\
    \ and user access"
- name: "secret"
  description: "Secret Management API. Secret is stored securely inside merlin and\
    \ can be used to run prediction job"
schemes:
- "http"
security:
- Bearer: []
paths:
  /v2/applications:
    get:
      tags:
      - "application"
      summary: "List CaraML applications"
      parameters: []
      responses:
        "200":
          description: "OK"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Application"
  /v1/projects:
    get:
      tags:
      - "project"
      summary: "List existing projects"
      description: "Projects can be filtered by optional `name` parameter"
      parameters:
      - name: "name"
        in: "query"
        required: false
        type: "string"
        x-exportParamName: "Name"
        x-optionalDataType: "String"
      responses:
        "200":
          description: "OK"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Project"
    post:
      tags:
      - "project"
      summary: "Create new project"
      parameters:
      - in: "body"
        name: "body"
        description: "Project object that has to be added"
        required: true
        schema:
          $ref: "#/definitions/Project"
        x-exportParamName: "Body"
      responses:
        "201":
          description: "Created"
          schema:
            $ref: "#/definitions/Project"
        "400":
          description: "Invalid request format"
        "409":
          description: "Project with the same name already exists"
  /v1/projects/{project_id}:
    get:
      tags:
      - "project"
      summary: "Get project"
      parameters:
      - name: "project_id"
        in: "path"
        description: "project id of the project to be retrieved"
        required: true
        type: "integer"
        x-exportParamName: "ProjectId"
      responses:
        "200":
          description: "Ok"
          schema:
            $ref: "#/definitions/Project"
        "404":
          description: "Project Not Found"
    put:
      tags:
      - "project"
      summary: "Update project"
      parameters:
      - name: "project_id"
        in: "path"
        description: "project id of the project to be updated"
        required: true
        type: "integer"
        x-exportParamName: "ProjectId"
      - in: "body"
        name: "body"
        description: "Project object that has to be updated"
        required: true
        schema:
          $ref: "#/definitions/Project"
        x-exportParamName: "Body"
      responses:
        "200":
          description: "Ok"
          schema:
            $ref: "#/definitions/Project"
        "400":
          description: "Invalid request format"
  /v1/projects/{project_id}/secrets:
    get:
      tags:
      - "secret"
      summary: "List secret"
      parameters:
      - name: "project_id"
        in: "path"
        required: true
        type: "integer"
        x-exportParamName: "ProjectId"
      responses:
        "200":
          description: "Ok"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Secret"
    post:
      tags:
      - "secret"
      summary: "Create secret"
      parameters:
      - name: "project_id"
        in: "path"
        required: true
        type: "integer"
        x-exportParamName: "ProjectId"
      - in: "body"
        name: "body"
        required: true
        schema:
          $ref: "#/definitions/Secret"
        x-exportParamName: "Body"
      responses:
        "201":
          description: "Created"
          schema:
            $ref: "#/definitions/Secret"
  /v1/projects/{project_id}/secrets/{secret_id}:
    get:
      tags:
      - "secret"
      summary: "Get secret"
      parameters:
      - name: "project_id"
        in: "path"
        required: true
        type: "integer"
        x-exportParamName: "ProjectId"
      - name: "secret_id"
        in: "path"
        required: true
        type: "integer"
        x-exportParamName: "SecretId"
      responses:
        "200":
          description: "Ok"
          schema:
            $ref: "#/definitions/Secret"
    delete:
      tags:
      - "secret"
      summary: "Delete secret"
      parameters:
      - name: "project_id"
        in: "path"
        required: true
        type: "integer"
        x-exportParamName: "ProjectId"
      - name: "secret_id"
        in: "path"
        required: true
        type: "integer"
        x-exportParamName: "SecretId"
      responses:
        "204":
          description: "No content"
    patch:
      tags:
      - "secret"
      summary: "Update secret"
      parameters:
      - name: "project_id"
        in: "path"
        required: true
        type: "integer"
        x-exportParamName: "ProjectId"
      - name: "secret_id"
        in: "path"
        required: true
        type: "integer"
        x-exportParamName: "SecretId"
      - in: "body"
        name: "body"
        required: false
        schema:
          $ref: "#/definitions/Secret"
        x-exportParamName: "Body"
      responses:
        "200":
          description: "Updated"
          schema:
            $ref: "#/definitions/Secret"
  /v1/projects/{project_id}/secret_storages:
    get:
      tags:
      - "secret_storage"
      summary: "List secret storage"
      parameters:
      - name: "project_id"
        in: "path"
        required: true
        type: "integer"
        x-exportParamName: "ProjectId"
      responses:
        "200":
          description: "Ok"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/SecretStorage"
    post:
      tags:
      - "secret_storage"
      summary: "Create secret storage"
      parameters:
      - name: "project_id"
        in: "path"
        required: true
        type: "integer"
        x-exportParamName: "ProjectId"
      - in: "body"
        name: "body"
        required: true
        schema:
          $ref: "#/definitions/SecretStorage"
        x-exportParamName: "Body"
      responses:
        "201":
          description: "Created"
          schema:
            $ref: "#/definitions/SecretStorage"
  /v1/projects/{project_id}/secret_storages/{secret_storage_id}:
    get:
      tags:
      - "secret_storage"
      summary: "Get secret storage"
      parameters:
      - name: "project_id"
        in: "path"
        required: true
        type: "integer"
        x-exportParamName: "ProjectId"
      - name: "secret_storage_id"
        in: "path"
        required: true
        type: "integer"
        x-exportParamName: "SecretStorageId"
      responses:
        "200":
          description: "Ok"
          schema:
            $ref: "#/definitions/SecretStorage"
    delete:
      tags:
      - "secret_storage"
      summary: "Delete secret storage"
      parameters:
      - name: "project_id"
        in: "path"
        required: true
        type: "integer"
        x-exportParamName: "ProjectId"
      - name: "secret_storage_id"
        in: "path"
        required: true
        type: "integer"
        x-exportParamName: "SecretStorageId"
      responses:
        "204":
          description: "No content"
    patch:
      tags:
      - "secret_storage"
      summary: "Update secret storage"
      parameters:
      - name: "project_id"
        in: "path"
        required: true
        type: "integer"
        x-exportParamName: "ProjectId"
      - name: "secret_storage_id"
        in: "path"
        required: true
        type: "integer"
        x-exportParamName: "SecretStorageId"
      - in: "body"
        name: "body"
        required: false
        schema:
          $ref: "#/definitions/SecretStorage"
        x-exportParamName: "Body"
      responses:
        "200":
          description: "Updated"
          schema:
            $ref: "#/definitions/SecretStorage"
securityDefinitions:
  Bearer:
    type: "apiKey"
    name: "Authorization"
    in: "header"
definitions:
  Application:
    type: "object"
    required:
    - "homepage"
    - "name"
    properties:
      name:
        type: "string"
      description:
        type: "string"
      homepage:
        type: "string"
      config:
        $ref: "#/definitions/Application_config"
    example:
      name: "name"
      description: "description"
      config:
        navigation:
        - destination: "destination"
          label: "label"
        - destination: "destination"
          label: "label"
        icon: "icon"
        api: "api"
      homepage: "homepage"
  Project:
    type: "object"
    required:
    - "name"
    properties:
      id:
        type: "integer"
        format: "int32"
      name:
        type: "string"
      mlflow_tracking_url:
        type: "string"
      administrators:
        type: "array"
        items:
          type: "string"
      readers:
        type: "array"
        items:
          type: "string"
      team:
        type: "string"
      stream:
        type: "string"
      labels:
        type: "array"
        items:
          $ref: "#/definitions/Label"
      created_at:
        type: "string"
        format: "date-time"
      updated_at:
        type: "string"
        format: "date-time"
    example:
      updated_at: "2000-01-23T04:56:07.000+00:00"
      readers:
      - "readers"
      - "readers"
      stream: "stream"
      name: "name"
      created_at: "2000-01-23T04:56:07.000+00:00"
      id: 0
      team: "team"
      mlflow_tracking_url: "mlflow_tracking_url"
      administrators:
      - "administrators"
      - "administrators"
      labels:
      - value: "value"
        key: "key"
      - value: "value"
        key: "key"
  Label:
    type: "object"
    properties:
      key:
        type: "string"
      value:
        type: "string"
    example:
      value: "value"
      key: "key"
  Secret:
    type: "object"
    required:
    - "data"
    - "name"
    properties:
      id:
        type: "integer"
        format: "int32"
      name:
        type: "string"
      data:
        type: "string"
      secret_storage_id:
        type: "integer"
        format: "int32"
      created_at:
        type: "string"
        format: "date-time"
      updated_at:
        type: "string"
        format: "date-time"
    example:
      data: "data"
      updated_at: "2000-01-23T04:56:07.000+00:00"
      name: "name"
      created_at: "2000-01-23T04:56:07.000+00:00"
      id: 0
      secret_storage_id: 6
  SecretStorage:
    type: "object"
    required:
    - "config"
    - "name"
    - "scope"
    - "type"
    properties:
      id:
        type: "integer"
        format: "int32"
      name:
        type: "string"
      type:
        type: "string"
        enum:
        - "vault"
        - "internal"
      scope:
        type: "string"
        enum:
        - "project"
        - "global"
      project_id:
        type: "integer"
        format: "int32"
      config:
        $ref: "#/definitions/SecretStorageConfig"
      created_at:
        type: "string"
        format: "date-time"
      updated_at:
        type: "string"
        format: "date-time"
    example:
      updated_at: "2000-01-23T04:56:07.000+00:00"
      project_id: 6
      scope: "project"
      name: "name"
      created_at: "2000-01-23T04:56:07.000+00:00"
      id: 0
      type: "vault"
      config:
        vault:
          mount_path: "mount_path"
          auth_method: "auth_method"
          role: "role"
          gcp_auth_type: "gcp_auth_type"
          service_account_email: "service_account_email"
          url: "url"
          path_prefix: "path_prefix"
  SecretStorageConfig:
    type: "object"
    properties:
      vault:
        $ref: "#/definitions/VaultSecretStorageConfig"
    example:
      vault:
        mount_path: "mount_path"
        auth_method: "auth_method"
        role: "role"
        gcp_auth_type: "gcp_auth_type"
        service_account_email: "service_account_email"
        url: "url"
        path_prefix: "path_prefix"
  VaultSecretStorageConfig:
    type: "object"
    required:
    - "auth_method"
    - "mount_path"
    - "path_prefix"
    - "url"
    properties:
      url:
        type: "string"
      role:
        type: "string"
      mount_path:
        type: "string"
      path_prefix:
        type: "string"
      auth_method:
        type: "string"
      gcp_auth_type:
        type: "string"
      service_account_email:
        type: "string"
    example:
      mount_path: "mount_path"
      auth_method: "auth_method"
      role: "role"
      gcp_auth_type: "gcp_auth_type"
      service_account_email: "service_account_email"
      url: "url"
      path_prefix: "path_prefix"
  Application_config_navigation:
    type: "object"
    properties:
      label:
        type: "string"
      destination:
        type: "string"
    example:
      destination: "destination"
      label: "label"
  Application_config:
    type: "object"
    properties:
      api:
        type: "string"
      icon:
        type: "string"
      navigation:
        type: "array"
        items:
          $ref: "#/definitions/Application_config_navigation"
    example:
      navigation:
      - destination: "destination"
        label: "label"
      - destination: "destination"
        label: "label"
      icon: "icon"
      api: "api"
